[package]
name = "wfc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.4.0"
ndarray = "0.15.6"
no-panic = "0.1.22"
rand = "0.8.5"
rayon = "1.7.0"
